### ISSUE TITLE
NPE on createClientTransaction

### ISSUE THREAD

**Issue by deruelle** [RestComm/jain-sip#114]
It seems sometimes the listeningpoint from the hop can be null.

```
Caused by: java.lang.NullPointerException
	at gov.nist.javax.sip.SipProviderImpl.createClientTransaction(SipProviderImpl.java:389) [jain-sip-ri-7.0.4.262.jar:7.0.4.262]
	at gov.nist.javax.sip.SipProviderImpl.getNewClientTransaction(SipProviderImpl.java:455) [jain-sip-ri-7.0.4.262.jar:7.0.4.262]
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1234)
```

**Comment by deruelle** [comment]
Closed by https://github.com/RestComm/jain-sip/commit/c27cffa699556ed848b84e81f96825f11e43d3df
