### ISSUE TITLE
ConcurrentModificationException when deleting listening point

### ISSUE THREAD

**Issue by 9a4gl** [RestComm/jain-sip#142]
When deleting listening point, sometimes exception is thrown with following stack trace:
```
[Logger]     java.util.ConcurrentModificationException
[Logger]         at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
[Logger]         at java.util.LinkedList$ListItr.next(LinkedList.java:888)
[Logger]         at gov.nist.javax.sip.stack.UDPMessageProcessor.stop(UDPMessageProcessor.java:317)
[Logger]         at gov.nist.javax.sip.stack.SIPTransactionStack.removeMessageProcessor(SIPTransactionStack.java:2471)
[Logger]         at gov.nist.javax.sip.SipStackImpl.deleteListeningPoint(SipStackImpl.java:1682)
[Logger]         at myapp.mymethod(myFile.java:123)
```

**Comment by jaimecasero** [comment]
hi @9a4gl this seems a concurrency issue, we will check this. Any hint on how to reproduce it? it seems you are delering the listening point, is this part of your app cleanup logic on app exit?

Would you be interested on contributing a patch here?

**Comment by 9a4gl** [comment]
Yes, it was when I was closing application and closing sip stack. It happened only in test cases when I do cleanup very soon after startup. I solved the problem by adding 1 sec sleep before cleanup.

**Comment by jaimecasero** [comment]
well, it seems to be a corner-case, where stack is stopped during initialization, not very common... this will have low priority...

**Comment by 9a4gl** [comment]
IMO, fix should be easy. In UDPMessageProcessor synchronize access to messageChannels. For example make it this.messageChannels = Collections.synchronizedList(new LinkedList());

**Comment by jaimecasero** [comment]
Agree fix should be easy. Actually i would better use CopyOnWriteArrayList instead of full synchronized collection if any, to prevent unnecesarry thread contention (this collection will be mostly mutated during stack initialization, and the rest should be traversals)....

**Comment by Ioana-dot** [comment]
@jaimecasero any updates on this issue ?
