### ISSUE TITLE
IOException on UDP scenario

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/jain-sip#53]
"But, every 3rd run I get the following issue. Could you take a look? There are other ERROR lines which I think are associated with this one.. Note, I am running SIPp with 2 concurrent calls, 10 calls max, 2CPS.

20:09:29,499 ERROR [stderr - 71] (MSS-Executor-Thread-1) java.io.IOException: Operation not permitted
20:09:29,499 DEBUG [com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA - 458] (MSS-Executor-Thread-0) APP-ID-0 - *** LEAVING SCHEDULETASK() **
20:09:29,499 DEBUG [com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates - 421] (MSS-Executor-Thread-0) Leaving Entering helperConnectLeg()
20:09:29,499 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at java.net.PlainDatagramSocketImpl.send(Native Method)
20:09:29,500 DEBUG [com.vendor.dialogic.javax.media.mscontrol.fsm.DlgcFSM - 91] (MSS-Executor-Thread-0) Leaving Condition{ DlgcXSdpPortManagerFM: event[evProcessSdpOffer(SDP)] ==> NextState:DlgcXIvrLegPendState)}
20:09:29,500 DEBUG [com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcNetworkConnectionProxy - 318] (MSS-Executor-Thread-0) Exiting SdpPortManagerProxy::processSdpOfferAsync Task run() => Media Server
20:09:29,500 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at java.net.DatagramSocket.send(DatagramSocket.java:698)
20:09:29,501 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.UDPMessageChannel.sendMessage(UDPMessageChannel.java:835)
20:09:29,501 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:281)
20:09:29,502 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPTransactionImpl.sendMessage(SIPTransactionImpl.java:892)
20:09:29,502 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendMessage(SIPClientTransactionImpl.java:475)
20:09:29,503 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1062)
20:09:29,503 INFO  [gov.nist.javax.sip.stack.UDPMessageChannel - 236] (Mobicents-SIP-Servlets-UDPMessageChannelThread-2) Setting SIPMessage peerPacketSource to: /146.152.122.168:5060
20:09:29,503 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1337)
20:09:29,504 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1009)

"

**Comment by jaimecasero** [comment]
There are two hypothesis to this behavior:
1- Thread concurrency as in http://stackoverflow.com/questions/28098386/plaindatagramsocketimpl-ioexception-operation-not-permitted
2- Traffic throttling done at sys level as in https://github.com/netty/netty/issues/1258

**Comment by jaimecasero** [comment]
More evidence on pace throttling http://oosnmp.net/pipermail/snmp4j/2014-October/005433.html

**Comment by jaimecasero** [comment]
[jain-sip-ri-1.2.X-SNAPSHOT.jar.zip](https://github.com/RestComm/jain-sip/files/95960/jain-sip-ri-1.2.X-SNAPSHOT.jar.zip)

This patch synchronizes the UDP sending, and uses an optional system property to provide basic throttling (use -DdatagramSocketThrottling=<milliSecond> to start java process).

**Comment by jaimecasero** [comment]
Another hypothesis would be firewall issues as in http://www.bhyuu.com/linux-udp-socket-sendto-operation-not-permitted/

**Comment by jaimecasero** [comment]
Can you check syslog for this trace (http://www.scriptscoop.net/t/62a8b22725d1/linux-udp-socket-sendto-operation-not-permitted.html)

"dropping packet"...

**Comment by jaimecasero** [comment]
Roman confirmed that disabling firewall removed the issue

**Comment by deruelle** [comment]
good investigation job @jaimecasero . We should start to create a new section in documentation http://docs.telestax.com/sip-servlets-homepage/ to log those common pitfalls, what do you think ?

**Comment by jaimecasero** [comment]
thanks.

Well it doesnt hurt to have one more section with some links to Github, and
a small description/solution.

I will add it to my TODO list

**Comment by lilydjwg** [comment]
Hi, not know what this project does, but I had the same problem and just solved it. EPERM when sending UDP very fast may be caused by iptables conntrack modules. [Don't track those packets](http://scriptscoop.sc0713.com/t/62a8b22725d1/linux-udp-socket-sendto-operation-not-permitted.html), and the problem will go (you can still use other parts of iptables).

I had this problem with sending DNS replies, and what I use is:
```
iptables -t raw -I OUTPUT -p udp -m udp --sport 53 -j NOTRACK
```
