### ISSUE TITLE
Support Out-Of-Dialog NOTIFY with no Event header

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/jain-sip#74]
Currently, out-of-dialog NOTIFY is rejected if no Event header is present. NOTIFY is supposed to be an in-dialog- msg with appropiate SUBSCRIBE in place. Nervetheless, out-of-dialog NOTIFY is a common hack (PUBLISH is a more appropiate way to accomplish that) used by many products, so a certain relaxation of validation could be useful in some cases

NOTIFY sip:cm-resubscribe@av.com SIP/2.0^M 
Record-Route: <sip:2d2ec52e@135.9.95.174;transport=tcp;lr>^M 
Route: <sip:135.9.95.74:15060;transport=TCP;lr>^M 
From: <sip:av.com>;tag=dbe099deeadf41e5af88050568bed24^M 
To: <sip:cm-resubscribe@av.com>^M 
Call-ID: dbe099deeadf41e5af88050568bed24^M 
CSeq: 1 NOTIFY^M 
Max-Forwards: 69^M 
P-Av-Transport: AP;fe=135.9.95.6:17810;ne=135.9.95.174:5060;tt=TCP;th^M 
Via: SIP/2.0/TCP 135.9.95.174;branch=z9hG4bKdbe09bdceadf41e5af89050568bed24-AP;ft=141064;rport=39011^M 
Via: SIP/2.0/TCP 135.9.95.6;branch=z9hG4bKdbe09bdceadf41e5af89050568bed24^M 
User-Agent: av CM/R017x.00.0.441.0^M 
Contact: <sip:135.9.95.6;transport=tcp>^M 
P-Asserted-Identity: <sip:135.9.95.6>^M 
Subscription-State: terminated^M 
Content-Length: 0^M 
^M 
: javax.sip.TransactionUnavailableException: Missing a required header : Event 
at gov.nist.javax.sip.SipProviderImpl.getNewServerTransaction(SipProviderImpl.java:476) 
at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processRequest(SipApplicationDispatcherImpl.java:820) 
at gov.nist.javax.sip.EventScanner.deliverRequestEvent(EventScanner.java:250) 
at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:146) 
at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) 
at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1340) 
at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:851) 
at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.processMessage(ConnectionOrientedMessageChannel.java:462) 
at gov.nist.javax.sip.parser.NioPipelineParser$Dispatch.run(NioPipelineParser.java:131) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
at gov.nist.javax.sip.MDCScheduledTHExecutor$MDCFuture.run(MDCScheduledTHExecutor.java:57) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.text.ParseException: Missing a required header : Event 
at gov.nist.javax.sip.message.SIPRequest.checkHeaders(SIPRequest.java:283) 
at gov.nist.javax.sip.SipProviderImpl.getNewServerTransaction(SipProviderImpl.java:474) 
... 16 more

**Comment by jaimecasero** [comment]
https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/message/SIPRequest.java#L283

The previous condition could have into account dialogId (from/to tag param), and in apply rejection just in case the dialogId is present:
            //https://github.com/RestComm/jain-sip/issues/74
            if (getFromHeader().getTag()!=null &&
                    getToHeader().getTag() != null && getHeader(EventHeader.NAME) == null)
                throw new ParseException(prefix + EventHeader.NAME, 0);
